### ISSUE TITLE
Release 5.2.16 forthcoming

### ISSUE THREAD

**Issue by Hainish** [EFForg/https-everywhere#9621]
cc @jsha @cooperq @pde @J0WI @fuglede @semenko @loveithateit @diracdeltas @jeremyn

Scheduled for 5/4

**Comment by Bisaloo** [comment]
Can we HSTS-prune this time please? Is it simply an oversight or is there a technical reason it wasn't done last time?

It would be really helpful for us contributors. I sometimes start working on updating a ruleset before realising it's now preloaded. It's just a waste of time.

**Comment by J0WI** [comment]
#8833 is resolved, no more downgrade rules 🎉

**Comment by Hainish** [comment]
I'm unable to make a release today, and we don't release on Fridays, so this will have to wait until Monday.

**Comment by Hainish** [comment]
release made!

**Comment by Hainish** [comment]
I didn't get the chance to include the HSTS script into the release process.  I'll run this separately tomorrow

**Comment by Bisaloo** [comment]
> I didn't get the chance to include the HSTS script into the release process. I'll run this separately tomorrow

@Hainish, I think you forgot. It would be great if you have the time to do this!

**Comment by Hainish** [comment]
I did! I'll try to get to it today, thanks for the reminder.

On May 12, 2017 2:39:46 AM PDT, Bisaloo <notifications@github.com> wrote:
>> I didn't get the chance to include the HSTS script into the release
>process. I'll run this separately tomorrow
>
>@Hainish, I think you forgot. It would be great if you have the time to
>do this!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/EFForg/https-everywhere/issues/9621#issuecomment-301032175

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Hainish** [comment]
@Bisaloo https://github.com/EFForg/https-everywhere/pull/9891 is the result of hsts-prune.
